# Generated by Django 5.1.2 on 2024-11-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='cantidad',
        ),
        migrations.AddField(
            model_name='producto',
            name='capacidad',
            field=models.IntegerField(default=0),
        ),
    ]
