# Generated by Django 5.1.2 on 2024-11-15 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0003_rename_cantidad_bodega_cantidad_art_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodega',
            name='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='bodega',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Inventario.bodega'),
        ),
    ]
