# Generated by Django 5.1.2 on 2024-11-15 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0006_alter_bodega_cantidad_art'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventario.bodega'),
        ),
    ]
