# Generated by Django 5.1.3 on 2024-11-19 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proveedor', '0001_initial'),
        ('Ubicacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='provincia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proveedores', to='Ubicacion.provincia'),
        ),
    ]
