# Generated by Django 5.1.2 on 2024-11-23 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0002_alter_venta_options_remove_detalle_venta_subtotal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='descuento',
        ),
    ]
