# Generated by Django 5.1.2 on 2024-11-24 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0004_detalle_venta_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='total_venta',
        ),
        migrations.AddField(
            model_name='detalle_venta',
            name='total_venta',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10),
        ),
    ]
